### ISSUE TITLE
TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by juanvillacortac** [voorjaar/svelte-windicss-preprocess#5]
I just tested the new 2.0.0 release in sveltejs/kit, but when I run the project throws:
```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at compileStyleSheet (/home/villacorta/Proyectos/svelte-experiments/node_modules/windicss/lib/index.js:626:10)
    at StyleSheet.build (/home/villacorta/Proyectos/svelte-experiments/node_modules/windicss/lib/index.js:668:16)
    at _preprocess (/home/villacorta/Proyectos/svelte-experiments/node_modules/svelte-windicss-preprocess/src/index.js:169:10)
    at Object.preprocess (/home/villacorta/Proyectos/svelte-experiments/node_modules/svelte/src/compiler/preprocess/index.ts:235:27)
    at markup (/home/villacorta/Proyectos/svelte-experiments/node_modules/svelte-sequential-preprocessor/src/main.ts:10:33)
    at Object.preprocess (/home/villacorta/Proyectos/svelte-experiments/node_modules/svelte/src/compiler/preprocess/index.ts:235:21)
    at Object.load (/home/villacorta/Proyectos/svelte-experiments/node_modules/@snowpack/plugin-svelte/plugin.js:105:11)
    at runPipelineLoadStep (/home/villacorta/Proyectos/svelte-experiments/node_modules/snowpack/lib/index.js:74471:28)
    at Object.buildFile (/home/villacorta/Proyectos/svelte-experiments/node_modules/snowpack/lib/index.js:74638:24)
    at /home/villacorta/Proyectos/svelte-experiments/node_modules/snowpack/lib/index.js:131382:41
    at buildFile (/home/villacorta/Proyectos/svelte-experiments/node_modules/snowpack/lib/index.js:131394:24)
    at Object.loadUrl (/home/villacorta/Proyectos/svelte-experiments/node_modules/snowpack/lib/index.js:131738:30)
    at /home/villacorta/Proyectos/svelte-experiments/node_modules/@sveltejs/kit/src/api/dev/index.js:162:14
```

The svelte.config.js is:

```javascript
const { typescript } = require('svelte-preprocess')
const windicss = require('svelte-windicss-preprocess')
const seqPreprocess = require('svelte-sequential-preprocessor')

const windi = {
  markup: windicss.preprocess({
    compile: true,          // false: interpretation mode; true: compilation mode
    globalPreflight: true,  // set preflight style is global or scoped
    globalUtility: true,    // set utility style is global or scoped
    prefix: 'tw-'           // set compilation mode style prefix
  }),
}

module.exports = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: seqPreprocess([
    typescript(),
    windi,
  ]),
  kit: {
    // By default, `npm run build` will create a standard Node app.
    // You can create optimized builds for different platforms by
    // specifying a different adapter
    adapter: '@sveltejs/adapter-node',

    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte'
  }
};
```

**Note:** I use **[svelte-sequential-preprocessor](https://www.npmjs.com/package/svelte-sequential-preprocessor)** for **svelte-preprocess**  support, but if I disable it, the problem persist.
**Note 2:** I tested the same **svelte-windicss-preprocess** on a vanilla sapper template and the problem persist, but without a descriptive error like sveltekit. Not tested on stock svelte template.

I'm very hyped with the tailwind.config.js support, thank!

**Comment by voorjaar** [comment]
This is a very helpful issue. The reason for this is there are components that do not contain any tailwind classes or style block.  https://github.com/voorjaar/windicss/commit/ef71ab89ae752bfa79c57926991b685879b4e38a already fix this.
