### ISSUE TITLE
add support for "disabled" attribute

### ISSUE THREAD

**Issue by xinsight** [voorjaar/svelte-windicss-preprocess#9]
I encountered an error while adding the disabled attribute to an element.

For example, the following all fail:

```
<button disabled>Login</button>
<button disabled="disabled">Login</button>
<button disabled={isLoading}>Login</button>
```

Example error:
```
[!] (plugin svelte) TypeError: i.value.map is not a function
src/Login.svelte
TypeError: i.value.map is not a function
    at /project-root/node_modules/svelte-windicss-preprocess/src/index.js:123:71
    at Array.forEach (<anonymous>)
    at Object.enter (/project-root/node_modules/svelte-windicss-preprocess/src/index.js:111:33)
    at visit (/project-root/node_modules/svelte/node_modules/estree-walker/src/estree-walker.js:51:10)
    at visit (/project-root/node_modules/svelte/node_modules/estree-walker/src/estree-walker.js:83:12)
    at visit (/project-root/node_modules/svelte/node_modules/estree-walker/src/estree-walker.js:83:12)
    at visit (/project-root/node_modules/svelte/node_modules/estree-walker/src/estree-walker.js:83:12)
    at visit (/project-root/node_modules/svelte/node_modules/estree-walker/src/estree-walker.js:83:12)
    at Object.walk (/project-root/node_modules/svelte/node_modules/estree-walker/src/estree-walker.js:2:9)
    at _preprocess (/project-root/node_modules/svelte-windicss-preprocess/src/index.js:101:16)
```

**Comment by voorjaar** [comment]
This issue is due to the feature of variant attribute provided by windicss. This feature allows you to use like `disabled="bg-gray-500 text-white"`, but this conflicts with the original html attribute and led to this issue.

Affected include `disabled required checked`, so from the next version these three attributes will be changed to `tw-disabled tw-required tw-checked`.
